### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by Ceydigitaluditha** [drtwisted/godot-google-play-games-services#4]
@drtwisted Thank you for building this repository. Please tell me how I init this library to my Godot script.Thank you

**Comment by drtwisted** [comment]
@Ceydigitaluditha you can use the following contruction:
```
var gpgs_instance = Globals.get_singleton("GodotPlayGameServices")
gpgs_instance.init(get_instance_ID()) # Normal init
gpgs_instance.init_with_debug(get_instance_ID()) # Debug init
```

**Comment by drtwisted** [comment]
@Ceydigitaluditha Does previous post answer your question?

**Comment by drtwisted** [comment]
I assume this issue as resolved. If you have got any questions left, please, create another issue or contact me by any means convinient for you.
